# Generated by Django 5.2.1 on 2025-05-12 20:32

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('methode', models.CharField(choices=[('MMONEY', 'Mobile Money'), ('CARTE', 'Carte Bancaire'), ('ESPECES', 'Espèces')], default='MMONEY', max_length=10, verbose_name='méthode de paiement')),
                ('statut', models.CharField(choices=[('ATTENTE', 'En attente'), ('REUSSI', 'Réussi'), ('ECHOUE', 'Échoué'), ('REMBOURSE', 'Remboursé')], default='ATTENTE', max_length=10, verbose_name='statut du paiement')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='montant payé')),
                ('date_paiement', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date de paiement')),
                ('transaction_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='ID de transaction externe')),
                ('reservation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='paiement', to='bookings.reservation', verbose_name='réservation')),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
                'ordering': ['-date_paiement'],
            },
        ),
    ]
