# Generated by Django 5.2.1 on 2025-05-13 19:21

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fichier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fichier', models.FileField(upload_to='fichiers/%Y/%m/%d/', verbose_name='fichier')),
                ('nom_fichier', models.CharField(blank=True, max_length=255, verbose_name='nom du fichier')),
                ('type', models.CharField(blank=True, max_length=100, verbose_name='type MIME')),
                ('date_upload', models.DateTimeField(default=django.utils.timezone.now, verbose_name="date d'upload")),
            ],
        ),
    ]
