# Generated by Django 5.2.1 on 2025-05-12 20:32

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=150, verbose_name='nom')),
                ('prenom', models.CharField(max_length=150, verbose_name='prénom')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('telephone', models.CharField(blank=True, max_length=20, null=True, verbose_name='téléphone')),
                ('type', models.CharField(choices=[('CLIENT', 'Client'), ('AGENT', 'Agent Immobilier'), ('ADMIN', 'Administrateur')], default='CLIENT', max_length=10, verbose_name='type')),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date de création')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='customuser_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='customuser_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AgentImmobilier',
            fields=[
            ],
            options={
                'verbose_name': 'Agent Immobilier',
                'verbose_name_plural': 'Agents Immobiliers',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.customuser',),
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.customuser',),
        ),
    ]
