# Generated by Django 5.2.1 on 2025-05-16 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('fichiers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='documents_kyc',
            field=models.ManyToManyField(blank=True, help_text="Documents KYC soumis par l'utilisateur (principalement pour les agents).", related_name='user_kyc_documents', to='fichiers.fichier', verbose_name='documents KYC'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='kyc_verified',
            field=models.BooleanField(default=False, help_text="Indique si les documents KYC de l'utilisateur (agent) ont été vérifiés et approuvés.", verbose_name='KYC vérifié'),
        ),
    ]
