# Generated by Django 5.2.1 on 2025-05-12 20:32

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('fichiers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Logement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=255, verbose_name='titre')),
                ('type', models.CharField(choices=[('MAISON', 'Maison'), ('APPART', 'Appartement'), ('STUDIO', 'Studio'), ('CHAMBRE', 'Chambre')], default='APPART', max_length=10, verbose_name='type de logement')),
                ('adresse', models.CharField(max_length=255, verbose_name='adresse')),
                ('description', models.TextField(verbose_name='description')),
                ('prix_par_nuit', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='prix par nuit')),
                ('equipements', models.TextField(blank=True, help_text="Liste d'équipements séparés par des virgules", verbose_name='équipements')),
                ('statut', models.CharField(choices=[('PUBLIE', 'Publié'), ('DESACTIVE', 'Désactivé'), ('ATTENTE', 'En attente de validation')], default='ATTENTE', max_length=10, verbose_name='statut')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(limit_choices_to={'type': 'AGENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='logements_proposes', to=settings.AUTH_USER_MODEL, verbose_name='agent immobilier')),
                ('favorited_by', models.ManyToManyField(blank=True, related_name='logements_favoris', to='accounts.client')),
                ('photos', models.ManyToManyField(blank=True, related_name='logements', to='fichiers.fichier', verbose_name='photos')),
            ],
        ),
        migrations.CreateModel(
            name='Disponibilite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_debut', models.DateField(verbose_name='date de début')),
                ('date_fin', models.DateField(verbose_name='date de fin')),
                ('est_disponible', models.BooleanField(default=True, verbose_name='est disponible')),
                ('logement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disponibilites', to='properties.logement', verbose_name='logement')),
            ],
            options={
                'verbose_name': 'Disponibilité',
                'verbose_name_plural': 'Disponibilités',
                'ordering': ['date_debut'],
                'constraints': [models.CheckConstraint(condition=models.Q(('date_fin__gte', models.F('date_debut'))), name='date_fin_gte_date_debut'), models.UniqueConstraint(fields=('logement', 'date_debut', 'date_fin'), name='unique_disponibilite_par_logement_et_dates')],
            },
        ),
    ]
