# Generated by Django 5.2.1 on 2025-05-12 20:32

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('note', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='note (1 à 5)')),
                ('texte', models.TextField(verbose_name='texte du commentaire')),
                ('date_publication', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date de publication')),
                ('valide_par_admin', models.BooleanField(default=False, verbose_name='validé par admin')),
                ('auteur', models.ForeignKey(limit_choices_to={'type': 'CLIENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='commentaires_laisses', to=settings.AUTH_USER_MODEL, verbose_name='auteur')),
                ('logement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaires', to='properties.logement', verbose_name='logement évalué')),
            ],
            options={
                'verbose_name': 'Commentaire',
                'verbose_name_plural': 'Commentaires',
                'ordering': ['-date_publication'],
            },
        ),
    ]
